language: python
jobs:
  include:
  - python: "3.3"
    dist: trusty
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8-dev"
  - python: pypy3
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install pydiatra $pyflakes
- python3 -m pip install restructuredtext-lint pygments
script:
- python3 -m pydiatra bluntweb
- python3 -m pyflakes bluntweb
- export PATH="$PWD:$PATH"
- export BROWSER="curl --head"
- bluntweb --help
- bluntweb google blunt web
- bluntweb wikiquote James Blunt
- bluntweb wikipedia web
- bluntweb wiktionary blunt
- bluntweb imdb blunt
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
