language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
install:
- pip install pydiatra
- pip install pyflakes
- pip install docutils pygments
script:
- python3 -m pydiatra bluntweb
- python3 -m pyflakes bluntweb
- export PATH="$PWD:$PATH"
- export BROWSER="curl --head"
- bluntweb --help
- bluntweb google blunt web
- bluntweb wikiquote James Blunt
- bluntweb wikipedia web
- bluntweb wiktionary blunt
- private/check-rst

# vim:ts=2 sts=2 sw=2 et
