#!/usr/bin/env python3

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import configparser
import os
import shutil
import subprocess
import urllib.parse

lambda: (yield from 0)  # Python >= 3.3 is required

def open_in_browser(url):
    for cmd in 'sensible-browser', 'xdg-open':
        if shutil.which(cmd):
            break
    subprocess.call([cmd, url])

def main():
    cp = configparser.ConfigParser(interpolation=None, default_section='')
    this = os.path.realpath(__file__)
    here = os.path.dirname(this)
    path = os.path.join(here, 'config')
    cp.read(path, encoding='ASCII')
    conf = cp['bluntweb']
    ap = argparse.ArgumentParser()
    sites = sorted(conf)
    ap.add_argument('-l', '--lang', default='en')
    ap.add_argument('site', metavar='SITE', choices=sites, help=' | '.join(sites))
    ap.add_argument('args', metavar='ARG', nargs='+')
    options = ap.parse_args()
    url_template = conf[options.site]
    variables = dict(
        args=' '.join(options.args),
        lang=options.lang
    )
    variables = dict(
        (k, urllib.parse.quote(v))
        for k, v in variables.items()
    )
    url = url_template.format(**variables)
    open_in_browser(url)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
